import Head from "next/head";
import { Inter } from "next/font/google";
import Home1 from "./components/Home/Home1";
import Header from "./components/Home/Header";
import Cards from "./components/Home/Cards";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home1 />
      <Cards />
    </>
  );
}
